# Generated by Django 5.2.1 on 2025-05-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='id',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
