# Generated by Django 5.2.1 on 2025-05-29 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_remove_customer_id_remove_loan_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='monthly_repayment',
            new_name='monthly_installment',
        ),
    ]
